# Generated by Django 4.2 on 2026-03-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_declined_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_exchange_variant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='return_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(blank=True, choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('refunded', 'Returned & Refunded'), ('exchanged', 'Returned & Exchanged')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_type',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('exchange', 'Exchange')], max_length=10, null=True),
        ),
    ]
