# Generated by Django 4.2 on 2026-03-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaam', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Leave blank to default to whatsapp_number@upi', max_length=50, null=True),
        ),
    ]
