# Generated by Django 4.2 on 2026-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaam', '0004_seller_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of parsed variants with stock counts'),
        ),
    ]
