# Generated by Django 4.2 on 2026-03-31 14:39

from django.db import migrations, models
import kaam.models


class Migration(migrations.Migration):

    dependencies = [
        ('kaam', '0005_add_variants_json_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=kaam.models.generate_product_id, editable=False, max_length=20),
        ),
    ]
