# Generated by Django 4.2 on 2026-03-31 14:56

from django.db import migrations, models
import kaam.models

def _dedupe_product_ids(apps, schema_editor):
    Product = apps.get_model('kaam', 'Product')
    db_alias = schema_editor.connection.alias
    products = Product.objects.using(db_alias).order_by('created_at', 'id')
    used = set(
        pid.strip()
        for pid in Product.objects.using(db_alias).values_list('product_id', flat=True)
        if pid and pid.strip()
    )
    seen = set()

    for product in products:
        current = (product.product_id or '').strip()
        if current and current not in seen:
            seen.add(current)
            continue

        base = f'P{product.id}'
        candidate = base[:20]
        idx = 1
        while not candidate or candidate in used or candidate in seen:
            suffix = f'-{idx}'
            candidate = f'{base[:20 - len(suffix)]}{suffix}'
            idx += 1

        product.product_id = candidate
        product.save(update_fields=['product_id'])
        used.add(candidate)
        seen.add(candidate)

class Migration(migrations.Migration):
    dependencies = [
        ('kaam', '0006_product_product_id'),
    ]

    operations = [
        migrations.RunPython(_dedupe_product_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=kaam.models.generate_product_id, editable=False, max_length=20, unique=True),
        ),
    ]
