# Generated by Django 4.2 on 2026-04-11 10:40

from django.db import migrations, models
import kaam.models


class Migration(migrations.Migration):

    dependencies = [
        ('kaam', '0008_seller_order_delivery_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, help_text='Business email for contact', max_length=254),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='product',
                    name='product_id',
                    field=models.CharField(default=kaam.models.generate_product_id, editable=False, max_length=20, unique=True),
                ),
            ],
            database_operations=[],
        ),
    ]
